### ISSUE TITLE
Remove the <hyprland/...> in border++ include directories to make the instructions from the wiki work

### ISSUE THREAD

**Issue by MathisP75** [hyprwm/hyprland-plugins#17] opened 2023-04-30 22:15 UTC

**Comment by vaxerski** [comment] 2023-04-30 22:18
The issue is with our migration to global headers, should update the wiki.

**Comment by MathisP75** [comment] 2023-04-30 22:21
Ah, makes sense

**Comment by vaxerski** [comment] 2023-04-30 22:32
blocked by https://github.com/hyprwm/Hyprland/pull/2201

**Comment by vaxerski** [comment] 2023-05-01 00:05
should be fixed and the wiki should be still valid, but the env is redundant now. I'll edit it.

**Closed** 2023-09-02 19:40 UTC
