### ISSUE TITLE
[Feature Request] hyprbars: Active/Inactive colors

### ISSUE THREAD

**Issue by Candyhands** [hyprwm/hyprland-plugins#232] opened 2024-10-13 07:50 UTC
It would be great if you could set a different bar and text color for inactive windows. Personally, that would help me distinguish the active from the inactive windows a little bit better than border color or transparency.  

E.g. the title bar for the active window is green, and the others are pink.

**Comment by Misterio77** [comment] 2024-12-10 02:24
Dupe of #72. This is already a feature (#192), just use the `plugin:hyprbars:bar_color` and `plugin:hyprbars:title_color` rules with the `focus:1` selector

**Closed** 2024-12-10 20:45 UTC
