### ISSUE TITLE
Hyprland crashes when in need for `hyprpm update`

### ISSUE THREAD

**Issue by alba4k** [hyprwm/hyprland-plugins#127] opened 2024-04-05 16:18 UTC
It's already happened multiple times to me that hyprland crashed on reload when hyprpm needed updates, which is especially annoying since I have `hyprpm reload` as exec-once in my config (ergo, once it crashes once I can't just restart it and fix the issue)

Not sure how to debug this.

[hyprlandCrashReport309844.txt](https://github.com/hyprwm/hyprland-plugins/files/14887645/hyprlandCrashReport309844.txt)

Also, was crashing on startup now too, but no update was needed. I had to comment that line in my config
[hyprlandCrashReport2719.txt](https://github.com/hyprwm/hyprland-plugins/files/14887702/hyprlandCrashReport2719.txt)

**Comment by vaxerski** [comment] 2024-04-05 18:43
couple things:
 - hyprpm lives in hyprland not -plugins
 - dupe of https://github.com/hyprwm/Hyprland/issues/5443

**Closed by vaxerski** 2024-04-05 18:43 UTC
